<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Pipelines" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <Authors>Charles Lee</Authors>
    <Description>BLE Nordic UART IDuplexPipe transport for CallAndResponse</Description>
  </PropertyGroup>

</Project>
