<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\CallAndResponse\CallAndResponse.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CallAndResponse.Test.Unit" />
  </ItemGroup>

  <PropertyGroup>
    <Authors>Charles Lee</Authors>
    <Description>A Modbus API using the CallAndResponse Transceiver</Description>
    <PackageTags>serial modbus</PackageTags>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageOutputPath>..\..\Output\Debug</PackageOutputPath>
  </PropertyGroup>
</Project>
