name: "Deploy to NuGet"

on: ["push"]

env:
  SOLUTION_PATH: 'Source\CallAndResponse.sln'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\Output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/call-and-response/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Pack project'
      run: dotnet pack ${{ env.SOLUTION_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }} -p:SymbolPackageFormat=snupkg

    - name: 'Push package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}